modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="fionamillenaire"
version="1.0.0"
displayName="FionaMillenaire"
authors="Fiona Danger"
description='''
A NeoForge mod adding Millénaire-inspired cultures, blocks, and worldbuilding content.
'''

entrypoint="com.fionadanger.fionamillenaire.fionamillenaire"

[[dependencies.fionamillenaire]]
modId="neoforge"
mandatory=true
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.fionamillenaire]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
